DATABASE_CONFIG_SECTION = 'DATABASE'
DATABASE_NAME_KEY = 'name'

DISCORD_CONFIG_SECTION = 'DISCORD'
DISCORD_TOKEN_FILE_KEY = 'token_file'

SERVER_CONFIG_SECTION = 'SERVER'
SERVER_WHITELIST_TARGET_KEY = 'whitelist_target_dir'
